#!/bin/bash

set -e
./dev
# python test.py
# in a scope, cd to tests/py and execute python test.py
(cd tests/py && python test.py)

echo "tearing down container"
docker-compose down >/dev/null 2>&1 &  # shut down the container in the background.
