#!/bin/bash

set -e


# Function to tear down the container
tear_down() {
    echo "tearing down container"
    docker-compose down >/dev/null 2>&1 &  # shut down the container in the background
}

# (cd tests/py && python test.py)
run_pytests() {
    # in a scope, cd to tests/py and execute python test.py
    (. ./activate.sh && python tests/py/test.py)
    test_exit_code=$?
    if [ $test_exit_code -ne 0 ]; then
        echo "Test failed with exit code $test_exit_code."
        exit $test_exit_code
    fi
}


run_jstests() {
    # in a scope, cd to tests/js and execute npm install and npm test
    (cd tests/js && npm install && npm test)
    test_exit_code=$?
    if [ $test_exit_code -ne 0 ]; then
        echo "Test failed with exit code $test_exit_code."
        exit $test_exit_code
    fi
}

# BEGIN EXECUTION OF SCRIPT

./dev

# Set up trap to ensure tear_down is called on exit
trap tear_down EXIT

run_pytests

# if --full in command args then cd to tests/js and execute npm install and npm test
# they are disabled by default because the js tests are still failing.
if [[ "$@" == *"--full"* ]]; then
    echo "Running JS tests"
    run_jstests
else
    exit 0
fi
